command:
  /start: UserService#start
  /task_list: UserService#list
  /group_list: GroupService#list

context:
  task/create: TaskService#create
  task/update: TaskService#update
  group/create: GroupService#create

callback:
  task/ask/create: TaskService#ask_create
  task/list: TaskService#list
  task/select/item: TaskService#select
  task/ask/done: TaskService#ask_done
  task/done/:id: TaskService#done
  task/change/:id: TaskService#change
  task/ask/update/:id: TaskService#ask_update
  task/not_done/:id: TaskService#not_done
  task/delete/:id: TaskService#delete

  group/list: GroupService#list
  group/ask/create: GroupService#ask_create
  group/ask/delete: GroupService#ask_delete
  group/delete/:id: GroupService#delete
  group/set_active/:id: GroupService#set_active

  common/cancel: CommonService#cancel
