command:
  /start: UserHandler#start
  /task_list: UserHandler#list
  /group_list: GroupHandler#list

context:
  task/create: TaskHandler#create
  task/update: TaskHandler#update
  group/create: GroupHandler#create

callback:
  task/ask/create: TaskHandler#ask_create
  task/list: TaskHandler#list
  task/select/item: TaskHandler#select
  task/ask/done: TaskHandler#ask_done
  task/done/:id: TaskHandler#done
  task/change/:id: TaskHandler#change
  task/ask/update/:id: TaskHandler#ask_update
  task/not_done/:id: TaskHandler#not_done
  task/delete/:id: TaskHandler#delete

  group/list: GroupHandler#list
  group/ask/create: GroupHandler#ask_create
  group/ask/delete: GroupHandler#ask_delete
  group/delete/:id: GroupHandler#delete
  group/set_active/:id: GroupHandler#set_active

  common/cancel: CommonHandler#cancel
