# config/database.yml

setup: &setup
  host: 'localhost'
  adapter: 'postgresql'
  encoding: utf-8
  username: "docker"
  password: "docker"

development:
  <<: *setup
  database: 'snap_feed_dev'

test:
  <<: *setup
  database: 'snap_feed_test'

production:
  host: 'dokku-postgres-db'
  adapter: 'postgresql'
  encoding: utf-8
  database: 'production'
  username: "postgres"
